# Generated by Django 4.1.7 on 2023-05-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailalert',
            name='air_quality',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emailalert',
            name='previous_air_quality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
